development:
  adapter: postgresql
  database: super_mart_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: super_mart__test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: super_mart__production
  pool: 5
  timeout: 5000